# Generated by Django 5.2.12 on 2026-03-19 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(blank=True)),
                ('payRate', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='LineManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('CONSULTANT', 'Consultant'), ('LINE_MANAGER', 'Line Manager'), ('ADMIN', 'Administrator'), ('FINANCE', 'Finance Team')], max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('timesheetID', models.AutoField(primary_key=True, serialize=False)),
                ('submitDate', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.consultant')),
                ('lineManager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.linemanager')),
            ],
        ),
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('payslipID', models.AutoField(primary_key=True, serialize=False)),
                ('totalHours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payRate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('totalPay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generatedDate', models.DateField(auto_now_add=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.consultant')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.timesheet')),
            ],
        ),
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hoursWorked', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField(blank=True)),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.timesheet')),
            ],
        ),
        migrations.AddField(
            model_name='linemanager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
