# Generated by Django 5.2.12 on 2026-04-07 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='id',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='payRate',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='skills',
        ),
        migrations.AddField(
            model_name='consultant',
            name='consultantId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='weekCommencing',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='weekEnding',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='lineManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.linemanager'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='submitDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('assignment_name', models.CharField(max_length=200)),
                ('week_started', models.DateField()),
                ('week_ended', models.DateField()),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.timesheet')),
            ],
        ),
    ]
