# Generated by Django 5.2.12 on 2026-04-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_consultant_id_remove_consultant_payrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='work_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('OVERTIME', 'Overtime'), ('SICK', 'Sick'), ('HOLIDAY', 'Holiday')], default='STANDARD', max_length=20),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='hoursWorked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
